### ISSUE TITLE
npm ERR! during setup

### ISSUE THREAD

**Issue by friebetill** [pixelated/pixelated-user-agent#891] opened 2016-12-28 11:08 UTC
I am installing the pixelated-user-agent, but run into this problem.

```
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm ERR! Linux 4.4.0-53-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! phantomjs-prebuilt@2.1.14 install: `node install.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the phantomjs-prebuilt@2.1.14 install script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the phantomjs-prebuilt package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs phantomjs-prebuilt
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls phantomjs-prebuilt
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/faraday/Dropbox/Freizeit/Projekte/Hacking/33C3/Pixelated/pixelated-user-agent/web-ui/npm-debug.log
```

Operating system: ubuntu 16.04 LTS

**Comment by tuliocasagrande** [comment] 2017-01-12 15:38
Hello @friebetill. Thanks for getting in touch.

It seems the problem isn't related with fsevents, because it's an optional dependency and npm knows how to handle it. Instead, the problem occurred with the installation of phantomjs-prebuilt.

I couldn't reproduce your error, but I've got a different one:

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! Linux 3.16.0-4-amd64
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! pixelated-user-agent-web-ui@0.0.0 postinstall: `bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the pixelated-user-agent-web-ui@0.0.0 postinstall script 'bower install'.
```

**Comment by anikarni** [comment] 2017-01-13 11:13
Hi @friebetill. It seems like this is a known error and there is an [open issue](https://github.com/Medium/phantomjs/issues/659) for phantomjs (which still doesn't have a valid solution, apparently).

We here at Pixelated use node version >= 6.2.2 and aren't having this issue, but a lot of people seem to have reported it with node 4. I just tried downgrading to your version, though, and didn't have any problems either, so I'm not sure this will solve it, but still, pixelated does require node > 6.

What do you think about upgrading your node version and trying again? Let us know if you still have issues!

@tuliocasagrande , I believe you were able to find the solution to the problem you were seeing, correct?

**Comment by tuliocasagrande** [comment] 2017-01-13 13:13
@anikarni No, I couldn't fix it.

**Comment by tuliocasagrande** [comment] 2017-01-13 16:08
Hello @anikarni, since this issue is being tracked in phantomjs, I'm going to close this!

@friebetill, if you need more help, feel free to open another issue.

**Closed by tuliocasagrande** 2017-01-13 16:08 UTC
Labels: bug, Ready to dev
