### ISSUE TITLE
The first email, after key renewal, was not signed

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#894] opened 2016-12-29 20:06 UTC
***Precondition***: a user with expired key

***Steps to reproduce***

1. Log in on Pixelated with some expired key user;
2. Send an email to some other regular user.

***Obtained result*** 
The email was received not signed.

***Expected result***
The email should be received signed.

PS: This behaviour was detected on [key_expiry](https://github.com/pixelated/pixelated-user-agent/tree/key_expiry) branch.

**Comment by thaissiqueira** [comment] 2016-12-29 20:12
This issue is related with #815

**Comment by tuliocasagrande** [comment] 2017-01-17 20:07
We were able to reproduce the problem and found out:

- This first email after key renewal **is being** signed with the new key, however, the recipient client:
    - first, uses the old key to verify the signature
    - then, updates the sender key
- On the second email after key renewal, the behavior is normalized.

A solution for that would be to update the sender key before verifying the signature, but we still need to analyze the code for that.

Before that, we should consider whether we want this verification to happen at all. In other words, do we want:
- The "Signed" flag means the email was simply signed
- The "Signed" flag means the email was signed using the key we have in store (current behaviour)

@SweetVirginia @olabini what do you think?

**Comment by olabini** [comment] 2017-01-18 11:50
OK let me first just say "ugh"

**Comment by olabini** [comment] 2017-01-18 11:51
Sorry - thinking about it. =)

**Comment by olabini** [comment] 2017-01-18 13:21
OK, so. Basically - while we still have the "Signed" flag in the UI, we should probably have it mean something more helpful than either of the two alternatives. Specifically, what I would expect it to mean would be
"The email was signed using a valid key for the email address the email came from" (and maybe also have it be a trusted key?

The problem is that GPG doesn't really require any of this, which is why Enigmail and other clients basically say "Signed by Ola Bini <ola@olabini.se>" separately from the place with the From address. If you don't do something like this, you can get into trouble like this:

Say that I send an email to Tulio saying "Yes, do it!" and I sign that email. Then, Denis could take the encrypted and signed content and resend it exactly as is from himself.

**Comment by tuliocasagrande** [comment] 2017-01-18 18:48
Hello @olabini, I agree with you and I think it's in accordance with the tooltips being developed at #828. We even have changed the "Signed" flag to **"Verified sender"** a few months ago and I forgot to double check my previous message. So please consider "Verified sender" instead of "Signed".

Adding more context. I've made some tests to confirm what we observed. I've sent some emails before and after changing the key:

```bash
# first email: the key attached was imported and used verify the signature
INFO SIGNATURE: valid; pubkey="E0794FCBA19E117712B1C696A9B1D5EC4327AB60"
# the key was changed!!!
# the old key was used to verify the signature, then the new key was imported
INFO SIGNATURE: invalid
# the new key was used to verify the signature
INFO SIGNATURE: valid; pubkey="7562972479F7716E31E9FFCDF702D5318D01C410"
```

The next step will be dig into `bitmask-dev/src/leap/bitmask/mail/incoming/service.py` and find out where this `valid/invalid` property is set.

**Comment by tuliocasagrande** [comment] 2017-01-19 16:07
Ok, I've understood the flow and I'm putting here for reference:

All begins at [_process_incoming_mail](https://0xacab.org/leap/bitmask-dev/blob/master/src/leap/bitmask/mail/incoming/service.py#L264). This method expects that Soledad already collected and encrypted the incoming email. So it receives a list of Soledad documents.

```bash
process_incoming_mail
_decrypt_doc # decrypts soledad doc
_maybe_decrypt_msg # decrypts the email and verify the signature
                   # it'll fetch from remote if the sender key doesn't exist or if it's expired
_maybe_extract_keys # extract attached key
#... continue the flow
```

So, this flow won't actually be a problem if the old key is really expired. We spotted this error in our tests, because we were forcing the key renewal (obviously to test), before the old key being actually expired.

Regardless, I still think we should tackle this issue, because there's the possibility of a user who replaced his/her key without the old one being expired.

**Comment by tuliocasagrande** [comment] 2017-01-19 17:25
Hey, I've just tested this can also happen between two pixelated providers, without even changing keys. Since we don't upload public keys to keyservers, the first email will also result in a "not signed" flag, then the attached key is added to the local keychain and used on subsequent emails.

**Comment by meskio** [comment] 2017-01-23 17:17
I agree that we should first import keys, and latter do the checking of singatures. We need to explore how hard will be to do that. As to import keys we need first to decrypt the email, and AFAIK currently we do both decrypt and signature checking in one go.


Keeping aside how we display (or not) the information that the signature is valid. In keymanager there is the storage of keys, that can contain as much garbage as we wish. And there is the information of what key is active, only active keys are trusted.

Right now we only check signatures (and do other operations) with the active key. There is not only the issue you have explained, also once you have flagged as active the new key (and 'deactivated' the old one) if an email arrives with an old signature (for example a delayed email) the verification will fail.

I don't think we should verify signatures with all keys in the keyring, as we might have untrusted keys. I think we should have one single active keys (that we encrypt for) and multiple old-active (let's find a better name, please). So all keys that used to be active, but now has being rotated, are in a list of keys 'semi-trusted' that we still use to verify signatures. Does that make sense?

**Comment by tuliocasagrande** [comment] 2017-01-24 12:42
Hello @meskio, thanks so much for your points of view.

As I understood, it seems we have 2 scenarios, that might need different solutions as well:

#### 1. the client can't verify the signature, because the key is new and the key was also sent attached
- this is the case when the user changed their keys or when users of 2 different providers exchange emails for the first time
- A solution for that would be to decrypt the message, import the attached key and latter check the signatures. But this can be tricky, because the decrypt/verify operation are done in one go, indeed.
- Solutions I've drafted so for:

**Solution A:** decrypt the message; in case the signature couldn't be verified and a key was imported; decrypt again. This second decrypt call would be an overload just to verify the signature with the new key.

**Solution B:** decrypt the message and detach the signature; in case the signature couldn't be verified and a key was imported; verify the detached signature with the new key. Although the second decryption call was changed by a verify call, which I assume is faster, it would be detaching the signature for every email. The better would be to benchmark both solutions to find out which is faster, more reliable, etc.
    

#### 2. the client might receive an email that was signed with an old key
- this is the delayed email case
- I'm wondering how possible or frequent that would be. Maybe out of scope for this issue?
- A solution for that would be to keep previous keys of known senders and use them in case of the active key failed to verify the signature. Is that correct?

Thoughts?

**Comment by tuliocasagrande** [comment] 2017-01-25 18:02
I opened a PR (https://0xacab.org/leap/bitmask-dev/merge_requests/64) with **Solution A**.

I chose this solution instead of Solution B, because, for the majority of emails, the procedure will remain the same, with only one decrypt call. Only in cases where the signature couldn't be verified and a new key was imported, it's going to perform a second decrypt call.

**Comment by meskio** [comment] 2017-01-26 15:28
I think is good to choose **Solution A** it's simpler to implement and the overhead as you say is not big.

I agree that the second scenario might be out of the scope of this issue and might not happen often. I'm happy to forget about it for now.

**Comment by varac** [comment] 2017-02-06 13:40
@tuliocasagrande what's the state ? The LEAP MR got already merged.

**Comment by tuliocasagrande** [comment] 2017-02-06 13:43
Yeah, it's done! 🎉

**Closed by tuliocasagrande** 2017-02-06 13:43 UTC
Labels: key expiry, Waiting for deploy
