### ISSUE TITLE
Increase SSL error handling

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#134] opened 2014-11-03 14:24 UTC
even with "--debug", i don't get more verbosity on why the useragent is not able to connect: 

```
pixelated-user-agent --config ~/thoughtworks/git/useragent-docker/config/pixelated.conf --debug

leap.common.events.server: INFO     Launching server on port 8090.
leap.common.events.daemon: INFO     Running server on port 8090.
requests.packages.urllib3.connectionpool: INFO     Starting new HTTPS connection (1): example.wazokazi.is
Can't connect to the requested provider
```

**Comment by varac** [comment] 2015-02-16 11:01
sorry to reopen, but i still think we should improve ssl error messages. 
When i encounter a "certificate verify failed" problem like this, i want to know what exactly fails (cert expired ? fingerprint mismatch ? CN doesn't match ? etc).

```
root@leap-wheezy:/vagrant/config# pixelated-user-agent --register try.pixelated-project.org varac102
2015-02-16 10:53:32+0000 [-] Log opened.
2015-02-16 10:53:32+0000 [-] Traceback (most recent call last):
2015-02-16 10:53:32+0000 [-]   File "/usr/bin/pixelated-user-agent", line 9, in <module>
2015-02-16 10:53:32+0000 [-]     load_entry_point('pixelated-user-agent==0.1', 'console_scripts', 'pixelated-user-agent')()
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/config/__init__.py", line 49, in initialize
2015-02-16 10:53:32+0000 [-]     register(*args.register[::-1])
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/config/register.py", line 23, in register
2015-02-16 10:53:32+0000 [-]     register_new_user(username, server_name)
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/register.py", line 30, in register_new_user
2015-02-16 10:53:32+0000 [-]     provider = LeapProvider(server_name, config)
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 28, in __init__
2015-02-16 10:53:32+0000 [-]     self.provider_json = self.fetch_provider_json()
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/pixelated/bitmask_libraries/provider.py", line 104, in fetch_provider_json
2015-02-16 10:53:32+0000 [-]     response = requests.get(url, verify=which_bundle(self), timeout=self.config.timeout_in_s)
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 55, in get
2015-02-16 10:53:32+0000 [-]     return request('get', url, **kwargs)
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
2015-02-16 10:53:32+0000 [-]     return session.request(method=method, url=url, **kwargs)
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 357, in request
2015-02-16 10:53:32+0000 [-]     resp = self.send(prep, **send_kwargs)
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/requests/sessions.py", line 460, in send
2015-02-16 10:53:32+0000 [-]     r = adapter.send(request, **kwargs)
2015-02-16 10:53:32+0000 [-]   File "/usr/lib/python2.7/dist-packages/requests/adapters.py", line 358, in send
2015-02-16 10:53:32+0000 [-]     raise SSLError(e)
2015-02-16 10:53:32+0000 [-] requests.exceptions.SSLError: [Errno 1] _ssl.c:504: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed

```

**Comment by shyba** [comment] 2015-04-23 13:57
https://github.com/pixelated-project/pixelated-user-agent/issues/375 changed this last log. This issue needs to be re-checked. :)

**Comment by shyba** [comment] 2015-10-28 22:02
Closing as duplicate of #375 and context is too old.

**Closed by shyba** 2015-10-28 22:02 UTC
Labels: Beginners
