### ISSUE TITLE
[bug] Feeback close button does not work

### ISSUE THREAD

**Issue by mnandri** [pixelated/pixelated-user-agent#653] opened 2016-03-21 10:53 UTC
When I click on the feedback exclamation mark icon then the feedback form shows on the right pane.
If I change my mind, and I click on the x close button at the upper left, it does not close the feedback form.

**Comment by re-nobre** [comment] 2016-03-21 13:25
Duplicate of #654

**Closed by re-nobre** 2016-03-21 13:25 UTC
Labels: 0 - Backlog, Beginners, bug, Hacknight
