### ISSUE TITLE
Compose window can't find all the keys

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#697] opened 2016-05-20 09:11 UTC
I am sending a mail to the team on wazokazi, and noticed that for two recipients, the keymanager seems to can't find the appropriate keys.
I didn't have time to investigate further.
See attached screenshot.

**Comment by varac** [comment] 2016-05-20 09:12
![screenshot_2016-05-20_11-09-41](https://cloud.githubusercontent.com/assets/488213/15423004/aba24054-1e7b-11e6-9e23-57e090c39f55.png)

**Comment by varac** [comment] 2016-05-20 09:21
hugh, i saved the draft, and opened it again. Now all keys are found.
Might be hard to reproduce. How i got this error was that i copied all email adr, clicked on "compose" and pasted the addresses.

**Comment by zaraG** [comment] 2016-05-20 09:25
I am just wondering if it just takes some time, to catch the keys, or if they really will not be encrypted.

**Comment by zaraG** [comment] 2016-05-20 09:41
I guess we should investigate, when this happens again, bc I can't reproduce it, even when I paste a huge list of recipients.

**Comment by varac** [comment] 2016-05-20 09:58
> I am just wondering if it just takes some time, to catch the keys, or if they really will not be encrypted.
i waited for some minutes. All the other keys got found in the first 1-5 secs.

**Comment by bwagnerr** [comment] 2016-05-20 14:35
Considering we have brittleness issues with load in general, I wouldn't be surprised if the problem was because it couldn't fetch the key or errored on volume of requests and appeared that it couldn't find the key instead

**Comment by re-nobre** [comment] 2016-06-08 15:23
@cz8s and me reproduce this now using the behave-testuser@wazokazi.is

I tried to send an email for the behave-testuser and got the orange lock nad cz8s got the green lock for the same address. There was not log for this and the email was sent.

So, we think it can be easy to reproduce.

**Comment by mnandri** [comment] 2016-06-14 15:40
very hard to reproduce... we need a more specific instruction...
for now closing... if it happens again, a new issue will be created.

**Closed** 2016-06-15 13:11 UTC
Labels: bug
