### ISSUE TITLE
Error when indexing new emails

### ISSUE THREAD

**Issue by giovaneliberato** [pixelated/pixelated-user-agent#589] opened 2016-02-01 15:28 UTC
This happens to my and @jeffhsta's account whenever we receive a new mail. Probably is something on indexing. We need to logout/login in order to see the email on inbox.

```
2016-02-01 15:24:05 [leap.common.events.server] DEBUG Publishing event: MAIL_UNREAD_MESSAGES
Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/search/__init__.py", line 162, in index_mails
    self._index_mail(writer, mail)
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/search/__init__.py", line 123, in _index_mail
    mdict = mail.as_dict()
AttributeError: 'NoneType' object has no attribute 'as_dict'
2016-02-01 15:24:05 [pixelated.adapter.listeners.mailbox_indexer_listener] ERROR 'NoneType' object has no attribute 'as_dict'
```

**Comment by re-nobre** [comment] 2016-06-13 11:44
Duplicate of https://github.com/pixelated/project-issues/issues/173
As there are more history in the other issue, I'm closing this one. :)

**Closed by re-nobre** 2016-06-13 11:44 UTC
Labels: bug, Search Index
