### ISSUE TITLE
Couldn't validate key and signature from different providers

### ISSUE THREAD

**Issue by giovaneliberato** [pixelated/pixelated-user-agent#588] opened 2016-02-01 13:04 UTC
Testing #576 I found that when exchanging mails between two providers the receiver couldn't process the key neither validate the signture.

<img width="806" alt="screen shot 2016-01-28 at 3 55 00 pm" src="https://cloud.githubusercontent.com/assets/2964631/12653807/4863bdfc-c5d8-11e5-9291-09e2f0b85cf4.png">

**Comment by re-nobre** [comment] 2016-06-13 09:19
hey, @zaraG!
Is it related with the issue: #703 ?

**Comment by zaraG** [comment] 2016-06-13 09:27
Nope, I am just upgrading a method which is validating if a fetched key is "trustful" if it has changed for some reason. We say, we trust the key, when the old persons key was signed by the new persons key (and other rules), but we just compare it with the long ID instead of the fingerprint.

But actually I am not sure if I understand the ticket. There are some plans on the LEAP roadmap which could go in that direction.

**Comment by deniscostadsc** [comment] 2016-06-14 17:15
I think this is not a bug. Provider doesn't publish their keys. So, different providers won't be able to get key from others providers.

**Comment by felixhammerl** [comment] 2016-06-17 14:48
here's the workflow to reproduce it:

* A sends a (unencrypted/signed) message to B including A's public key: Message is shown as unverified/unencrypted
* A sends another (unencrypted/signed) message to B including A's public key: Message is shown as unverified/unencrypted, even though B should already have A's public key
* B send a (encrypted/signed) message to A: : Message is shown as unverified/encrypted, even though the message contains A's public key
* A sends another (encrypted/signed) message to B: Message is shown as verified/encrypted
* any following thing is singed/encrypted

**Comment by felixhammerl** [comment] 2016-06-17 14:50
apparently, we don't trust a public key unless we have used it to send an email to that address at least once.

**Comment by zaraG** [comment] 2016-06-27 15:42
As we said, we will continue after the weekly on this ticket:

...if this ticket is about, communication between different Pix/LEAP providers, I am pretty sure LEAP folks are currently on it.

**Comment by zaraG** [comment] 2016-06-27 15:45
...if it is about something else, we might clarify that first..

**Comment by re-nobre** [comment] 2016-09-28 19:39
it is related with LEAP decisions, I will bring this topic on next leap call and close this issue in pixelated repo.

**Closed** 2016-09-28 19:40 UTC
Labels: bug, Signed/Encrypted Status
