### ISSUE TITLE
Useragent login page fails to load

### ISSUE THREAD

**Issue by varac** [pixelated/pixelated-user-agent#823] opened 2016-11-21 11:05 UTC
Currently, https://dev.pixelated-project.org:8080 fails to load, my browser shows me this:

```
The connection to dev.pixelated-project.org:8080 was interrupted while the page was loading.
```

In the logfile we see these tracebacks:

```
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: 2016-11-21 10:53:30 [log_legacy] CRITICAL Unhandled Error
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: Traceback (most recent call last):
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-package
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: return context.call({ILogContext: newCtx}, func, *args, **kw)
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-package
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: return self.currentContext().callWithContext(ctx, func, *args, **kw)
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-package
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: return func(*args,**kw)
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-package
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: why = selectable.doRead()
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: --- <exception caught here> ---
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-package
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: transport = self.transport(skt, protocol, addr, self, s, self.reactor)
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-package
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: self.startReading()
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-package
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: self.reactor.addReader(self)
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-package
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: EPOLLIN, EPOLLOUT)
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-package
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: self._poller.modify(fd, flags)
Nov 21 10:53:30 dev1 pixelated-user-agent[4858]: exceptions.IOError: [Errno 2] No such file or directory
```

restarting `pixelated-server` fixes this.

**Comment by olabini** [comment] 2017-01-20 19:07
I think that #913 is a duplicate of this one.

**Closed** 2017-03-22 12:10 UTC
Labels: bug
