### ISSUE TITLE
Create option to reset acount data

### ISSUE THREAD

**Issue by dudadornelles** [pixelated/pixelated-user-agent#235] opened 2015-01-20 14:12 UTC
As a developer, I would like to be able to wipe the data of my account so I can keep on using it in case it has some bad data.

For that we _cant_ delete the priv/pub keys, but we can delete all the mail/mailbox/recent flags/index data (basically everything but the priv/pub keys).

**Comment by GavinSchalliol** [comment] 2015-04-22 09:41
Is this a duplicate of #345/#346?

**Comment by tiagoferraz** [comment] 2015-04-22 12:43
Yes. Since the code from this US is valid to reset account on any environment and from any user, thus covering these 2 you  mentioned. So they can be closed if they are open.

**Comment by bwagnerr** [comment] 2015-08-10 19:35
There's the possibility to reset the data directly from the command line for development purpose currently, so closing this

**Closed by bwagnerr** 2015-08-10 19:35 UTC
