### ISSUE TITLE
user-agent failed with soledad error

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#706] opened 2016-06-07 12:50 UTC
I don't know how to reproduce this:

```
2016-06-07T07:18:45.461831+02:00 unstable1 pixelated-user-agent[16527]: 2016-06-07 07:18:45 [twisted] CRITICAL
2016-06-07T07:27:19.748721+02:00 unstable1 pixelated-user-agent[16527]: 2016-06-07 07:27:19 [pixelated.bitmask_libraries.nicknym] INFO Generating keys - this could take a while...
2016-06-07T07:29:51.369756+02:00 unstable1 pixelated-user-agent[16527]: 2016-06-07 07:29:51 [gnupg] WARNING Using untrusted key!
2016-06-07T08:27:15.390120+02:00 unstable1 pixelated-user-agent[16527]: 2016-06-07 08:27:15 [pixelated.bitmask_libraries.nicknym] INFO Generating keys - this could take a while...
2016-06-07T08:31:35.560171+02:00 unstable1 pixelated-user-agent[16527]: 2016-06-07 08:31:35 [leap.soledad.client.api] ERROR Soledad exception when syncing!
2016-06-07T08:31:35.560190+02:00 unstable1 pixelated-user-agent[16527]: *--- Failure #13515 ---
2016-06-07T08:31:35.560202+02:00 unstable1 pixelated-user-agent[16527]: Failure: u1db.errors.HTTPError: HTTPError(500)
2016-06-07T08:31:35.560213+02:00 unstable1 pixelated-user-agent[16527]: *--- End of Failure #13515 ---
2016-06-07T08:31:35.566454+02:00 unstable1 pixelated-user-agent[16527]: 2016-06-07 08:31:35 [pixelated.resources.login_resource] INFO Login Error for behave-testuser

```

**Comment by re-nobre** [comment] 2016-06-13 11:46
hey, @mnandri 
Do you think it's related with this issue: https://github.com/pixelated/puppet-pixelated/issues/43?

**Comment by mnandri** [comment] 2016-06-14 15:58
could be related... but it looks more like the http requests to soledad server was not successful... either a 503 response or invalid json response
I suggest we don't sweat over this... and wait for it to happen again.
@cz8s @re-nobre

**Comment by re-nobre** [comment] 2016-06-14 16:15
So, should we close this issue and reopen if the problem happen again?

**Comment by anikarni** [comment] 2017-01-20 13:44
Following suggestions above, closing this issue since it has not yet been reproduced.

**Closed by anikarni** 2017-01-20 13:44 UTC
Labels: bug
