### ISSUE TITLE
Understanding errors: add traceback of "Unhandled error in Deferred" error to logs

### ISSUE THREAD

**Issue by deniscostadsc** [pixelated/pixelated-user-agent#952] opened 2017-01-31 19:08 UTC
Description
--
When happen an "Unhandled error in Deferred" on pixelated-user-agent log
I want to able to see the traceback of the on the logs
So I can understand the root cause of the problem.

Context
--
We saw the  "Unhandled error in Deferred" error lot of time on wazokazi.is and a few time on unstable. And this is messing with our logs, so we can't debug the errors properly!

As we don't know what exactly what happened in the error we also don't know describe how to reproduce this error.

A possible reference about the problem: http://twistedmatrix.com/documents/current/core/howto/defer.html#unhandled-errors

**Comment by tuliocasagrande** [comment] 2017-02-06 18:28
One way [of many] to reproduce this:

1- Write an email
2- Click on the send button and immediately close the tab.

The log will catch:

```
2017-02-06 18:09:57 [pixelated.resources.mails_resource] ERROR error occurred while sending: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
2017-02-06 18:09:57 [twisted.internet.defer] CRITICAL Unhandled error in Deferred:
2017-02-06 18:10:00 [leap.bitmask.mail.outgoing.service] INFO Message sent from dean@staging.pixelated-project.org to dean@staging.pixelated-project.org
```

After this point, the `CRITICAL Unhandled error in Deferred:` is getting logged in different intervals, between 1 ~ 30 seconds.

---

Concerning the other error message, the email was successfully delivered, but when the server tried to return the "Your message was sent!" to the client, the connection was closed. This problem will be fixed on #957.

**Comment by tuliocasagrande** [comment] 2017-02-06 21:13
It seems it's a bug of twisted's new logging system (https://twistedmatrix.com/trac/ticket/7927 - last activity was 10 days ago). When the log message is formatted, the traceback information isn't printed.

I was able to log correctly when I removed the formatter:

```
2017-02-06T21:04:35+0000 [pixelated.resources.mails_resource#error] error occurred while sending: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
2017-02-06T21:04:35+0000 [twisted.internet.defer#critical] Unhandled error in Deferred:

Traceback (most recent call last):
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1174, in _inlineCallbacks
    deferred.errback()
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/vagrant/service/pixelated/resources/mails_resource.py", line 195, in onError
    respond_json_deferred({'message': 'an error occurred while sending'}, request, status_code=422)
  File "/vagrant/service/pixelated/resources/__init__.py", line 50, in respond_json_deferred
    request.finish()
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/web/server.py", line 224, in finish
    return http.Request.finish(self)
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/web/http.py", line 871, in finish
    "Request.finish called on a request after its connection was lost; "
exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
2017-02-06T21:04:37+0000 [leap.bitmask.mail.outgoing.service#info] Message sent from dean@staging.pixelated-project.org to dean@staging.pixelated-project.org
```

**Comment by tuliocasagrande** [comment] 2017-02-07 17:20
I just found we were getting an exception while formatting those `Unhandled error in Deferred` events.

The reason for this is because the unhandled error in deferred emits two log events:
```
{'log_namespace': 'twisted.internet.defer', 'log_level': <LogLevel=critical>, 'log_logger': <Logger 'twisted.internet.defer'>, 'log_format': 'Unhandled error in Deferred:', 'log_time': 1486473793.062178, 'log_source': None, 'isError': True}
{'log_namespace': 'twisted.internet.defer', 'log_level': <LogLevel=critical>, 'debugInfo': '', 'log_source': None, 'log_logger': <Logger 'twisted.internet.defer'>, 'log_time': 1486473793.063067, 'log_format': None, 'log_failure': <twisted.python.failure.Failure exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.>}
```

As described at https://twistedmatrix.com/trac/ticket/7927, the second log event (which has the traceback), has `'log_format': None`, so we were getting the following exception:
```
coercing to Unicode: need string or buffer, NoneType found
```

I changed to access the `log_format` attribute in a safer way and also added a fallback to guarantee the log event is always consumed.

The traceback is automatically appended to the output (https://twistedmatrix.com/documents/current/core/howto/logger.html#capturing-failures), so I couldn't add timestamps to each line, but this is probably going to change in new versions of twisted.

Final output:
```
2017-02-07 17:13:34 [pixelated.resources.mails_resource] ERROR error occurred while sending: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
2017-02-07 17:13:34 [twisted.internet.defer] CRITICAL Unhandled error in Deferred:
2017-02-07 17:13:34 [twisted.internet.defer] CRITICAL
Traceback (most recent call last):
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1184, in gotResult
    _inlineCallbacks(r, g, deferred)
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1174, in _inlineCallbacks
    deferred.errback()
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 434, in errback
    self._startRunCallbacks(fail)
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 501, in _startRunCallbacks
    self._runCallbacks()
--- <exception caught here> ---
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 588, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/vagrant/service/pixelated/resources/mails_resource.py", line 195, in onError
    respond_json_deferred({'message': 'an error occurred while sending'}, request, status_code=422)
  File "/vagrant/service/pixelated/resources/__init__.py", line 50, in respond_json_deferred
    request.finish()
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/web/server.py", line 224, in finish
    return http.Request.finish(self)
  File "/home/vagrant/.venvs/pixua/local/lib/python2.7/site-packages/twisted/web/http.py", line 871, in finish
    "Request.finish called on a request after its connection was lost; "
exceptions.RuntimeError: Request.finish called on a request after its connection was lost; use Request.notifyFinish to keep track of this.
```

**Comment by anikarni** [comment] 2017-02-07 19:06
@tuliocasagrande , as @varac mentioned, it seems parsing of this file requires that each line of the log should be logged as a new entry (with time and date at the beginning of the line). Did you take a look at whether this is possible? @varac , is this what you had mentioned?

**Comment by tuliocasagrande** [comment] 2017-02-08 12:39
@anikarni yes, I did.
Twisted's logger appends unhandled deferred tracebacks automatically and I couldn't find a way to surpass it.

**Comment by varac** [comment] 2017-02-09 09:23
>  as @varac mentioned, it seems parsing of this file requires that each line of the log should be logged as a new entry (with time and date at the beginning of the line). Did you take a look at whether this is possible? @varac , is this what you had mentioned?

Yes indeed. I cant remember, but are I guess we are logging to syslog right ?

**Comment by thaissiqueira** [comment] 2017-02-09 12:44
We saw the commit is already on production. So we are moving the issue to done.

**Closed** 2017-02-09 12:45 UTC
Labels: Tech story
