### ISSUE TITLE
pipeline for try hangs on user creation

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#469] opened 2015-09-25 14:46 UTC
the pipeline for try runs pixelated-register
to create the users alice,eve and bob.
the accounts work, but the pipeline never finishes

**Comment by kaeff** [comment] 2015-10-14 16:24
Duplicate of #480 ? The pipeline is green again, can be closed?

**Comment by cz8s** [comment] 2015-10-14 16:45
Yes

**Closed** 2015-10-14 16:57 UTC
