### ISSUE TITLE
RevisionConflict reappearing

### ISSUE THREAD

**Issue by cz8s** [pixelated/pixelated-user-agent#582] opened 2016-01-27 12:58 UTC
we deleted the docker image and the leapfolder but 
the logs still show that the RevisionConflict error still appears.

Here comes the log:

```
2016-01-27 11:55:20 [leap.common.events.server] DEBUG Publishing event: KEYMANAGER_KEY_FOUND
2016-01-27 11:55:21 [leap.mail.incoming.service] INFO An error has ocurred adding attached key for gil@wazokazi.is: FirstError[#0, [Failure instance: Traceback: <class 'u1db.errors.RevisionConflict'>:
/usr/lib/python2.7/threading.py:810:__bootstrap_inner
/usr/lib/python2.7/threading.py:763:run
/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py:46:work
/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/_threads/_team.py:190:doWork
--- <exception caught here> ---
/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/threadpool.py:246:inContext
/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/threadpool.py:262:<lambda>
/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py:118:callWithContext
/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py:81:callWithContext
/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/adbapi.py:271:_runInteraction
/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/adbapi.py:238:_runU1DBQuery
/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/sqlcipher.py:278:put_doc
/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/u1db/backends/sqlite_backend.py:371:put_doc
]]
2016-01-27 11:55:21 [leap.keymanager] INFO Fetch key for gil@wazokazi.is from https://wazokazi.is/key/gil
2016-01-27 11:55:21 [requests.packages.urllib3.connectionpool] INFO Starting new HTTPS connection (1): wazokazi.is
2016-01-27 11:55:21 [leap.keymanager] WARNING There was a problem fetching key: [Errno 2] No such file or directory
2016-01-27 11:55:21 [leap.mail.incoming.service] WARNING Url from OpenPGP header https://wazokazi.is/key/gil failed
2016-01-27 11:55:21 [twisted] INFO adding message f86bc9d6-0bbf-4b61-b1fa-e7ac7bb7c47c to local db
Unhandled error in Deferred:
2016-01-27 11:55:21 [twisted] CRITICAL Unhandled error in Deferred:


Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/_threads/_threadworker.py", line 46, in work
    task()
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 190, in doWork
    task()
--- <exception caught here> ---
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
    result = inContext.theWork()
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
    return self.currentContext().callWithContext(ctx, func, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
    return func(*args,**kw)
  File "/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/adbapi.py", line 271, in _runInteraction
    result = interaction(trans, *args, **kw)
  File "/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/adbapi.py", line 238, in _runU1DBQuery
    return meth(*args, **kw)
  File "/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/sqlcipher.py", line 278, in put_doc
    doc_rev = sqlite_backend.SQLitePartialExpandDatabase.put_doc(self, doc)
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/u1db/backends/sqlite_backend.py", line 371, in put_doc
    raise errors.RevisionConflict()
u1db.errors.RevisionConflict:
2016-01-27 11:55:21 [twisted] CRITICAL
```

**Comment by cz8s** [comment] 2016-02-03 16:06
happened again:
2016-02-03T15:55:40Z e67504180476 giovane.user_agent[15387] Failure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <class 'u1db.errors.RevisionConflict'>:

**Comment by cz8s** [comment] 2016-02-03 16:06
because I have the task to make the user-agent logs less noisy, I am moving this to ready

**Comment by shyba** [comment] 2016-02-03 17:35
Keymanager is currently having a lot of it.
I will use what I learned there recently and talk to meskio if I find the root cause.

**Comment by bwagnerr** [comment] 2016-02-18 18:03
@cz8s, just to add to the discussion, we added a filter on logwatch for that error previously, because it doesn't break the user agent and is corrected on a later sync.

**Comment by cz8s** [comment] 2016-02-18 18:08
Should we move to the backlog then?

**Comment by bwagnerr** [comment] 2016-02-18 18:11
If @shyba thinks he has an idea to fix this, maybe we should do it

**Comment by re-nobre** [comment] 2016-06-08 15:26
hey,

as @shyba  is not having time to help and this bug didn't show for a long time, we are closing this issue.
If it happen again, we can reopen or create a new one.

**Comment by thaissiqueira** [comment] 2017-03-06 17:55
This error start to show up again:

```
C Mar 2 17:59:20 pixelated pixelated-user-agent[20837]: 2017-03-02 17:59:20 [pixelated.resources.login_resource] ERROR Login error during <username> services setup: FirstError[#13, [Failure instance: Traceback: <class 'leap.soledad.common.l2db.errors.RevisionConflict'>:
. Mar 2 17:59:20 pixelated pixelated-user-agent[20837]: /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py:434:errback
. Mar 2 17:59:20 pixelated pixelated-user-agent[20837]: /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py:501:_startRunCallbacks
. Mar 2 17:59:20 pixelated pixelated-user-agent[20837]: /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py:588:_runCallbacks
. Mar 2 17:59:20 pixelated pixelated-user-agent[20837]: /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py:1184:gotResult
. Mar 2 17:59:20 pixelated pixelated-user-agent[20837]: --- <exception caught here> ---
. Mar 2 17:59:20 pixelated pixelated-user-agent[20837]: /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py:1126:_inlineCallbacks
. Mar 2 17:59:20 pixelated pixelated-user-agent[20837]: /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/failure.py:389:throwExceptionIntoGenerator
/errors.RevisionConflict()
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: --- <exception caught here> ---
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1126, in _inlineCallbacks
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: result = result.throwExceptionIntoGenerator(g)
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: return g.throw(self.type, self.value, self.tb)
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/src/leap.bitmask/src/leap/bitmask/keymanager/openpgp.py", line 600, in reset_sign_used
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: yield self.put_key(key, key_renewal=True)
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: result = inContext.theWork()
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: return self.currentContext().callWithContext(ctx, func, *args, **kw)
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: return func(*args,**kw)
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/adbapi.py", line 273, in _runInteraction
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: result = interaction(trans, *args, **kw)
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/adbapi.py", line 240, in _runU1DBQuery
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: return meth(*args, **kw)
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/src/leap.soledad.client/client/src/leap/soledad/client/sqlcipher.py", line 284, in put_doc
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: doc_rev = sqlite_backend.SQLitePartialExpandDatabase.put_doc(self, doc)
. Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: File "/usr/share/python/pixelated-user-agent/src/leap.soledad.common/common/src/leap/soledad/common/l2db/backends/sqlite_backend.py", line 368, in put_doc
C Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: raise errors.RevisionConflict()
C Mar 2 17:59:25 pixelated pixelated-user-agent[20837]: leap.soledad.common.l2db.errors.RevisionConflict:
```

**Comment by deniscostadsc** [comment] 2017-05-15 14:07
Closing this issue to transfer it to [Soledad repository](https://0xacab.org/leap/soledad/issues/8851).

**Closed by deniscostadsc** 2017-05-15 14:07 UTC
Labels: bug, Logs
