### ISSUE TITLE
Fix memory leak

### ISSUE THREAD

**Issue by thaissiqueira** [pixelated/pixelated-user-agent#782] opened 2016-09-13 19:23 UTC
Goals:

- Find a way to identify possible place where the memory is leaked.
- Fix the memory leak in the identified places.

**Comment by rdevries-thoughtworks** [comment] 2016-09-14 07:27
Is this a duplicate of #780? If not, what exactly is the difference?

**Comment by bwagnerr** [comment] 2016-09-14 13:26
@rdevries-thoughtworks hey!

I believe #780 is one manifestation of this more broad problem. From that issue, I take that we should remove/disable the smoke-tests on all environments for now (because they worsen the problem) and create an issue to fix the memory leak, hence this issue.

Does it make sense? We should also comment on that one to make it clearer

**Comment by rdevries-thoughtworks** [comment] 2016-09-14 13:30
@bwagnerr makes sense, indeed, if there is a separate memory leak related to the attachments; this is not yet entirely clear to me. I hope to talk to @shyba sometime soon to determine that.

**Comment by bwagnerr** [comment] 2016-09-14 13:38
I don't think there's a separated memory leak when using attachments, it is just that the memory leak is way more evident when handling with huge documents

**Comment by olabini** [comment] 2016-09-16 13:43
@rdevries-thoughtworks I see you've been investigating using Manhole - this makes me a bit uncomfortable, since manhole is a way of dumping thread dumps - something I have recommended against - it is unlikely to tell you the problem causing the memory leak. Instead, I would prefer approaches using dumps of live object counts (like a heap dump).

**Comment by rdevries-thoughtworks** [comment] 2016-09-16 18:53
@olabini actually manhole is an interactive Python shell with which you can inspect the process state at any moment, not specifically for thread dumps. I intend to use it for interactively getting heap dumps (and diffs between them) from guppy.

**Comment by olabini** [comment] 2016-09-19 13:21
Ah, ok. Didn't know you could do those things too - the docs for it seems to heavily emphasize the thread dumping functionality.

**Comment by varac** [comment] 2016-09-21 09:42
So there's an interesting observation.
@thaissiqueira deployed leap_platform on Tue 19, 19:43 CEST:

```
--- pixelated-platform-environments/pixelated-project.org ‹master› » leap history dev1
 = dev1.dev.pixelated-project.org
   - Sep 06 19:25:01 dev1: STARTING APPLY {user: dcosta, platform: 0.9, leap_cli: 1.9}
   - Sep 06 19:26:15 dev1: APPLY COMPLETE (changes made) {user: dcosta, platform: 0.9, leap_cli: 1.9}
   - Sep 06 19:43:08 dev1: STARTING APPLY {user: dcosta, platform: 0.9, leap_cli: 1.9}
   - Sep 06 19:44:21 dev1: APPLY COMPLETE (changes made) {user: dcosta, platform: 0.9, leap_cli: 1.9}
   - Sep 19 19:28:27 dev1: STARTING APPLY {user: tsiqueir, platform: 0.9, leap_cli: 1.9}
   - Sep 19 19:28:33 dev1: APPLY COMPLETE (failed) {user: tsiqueir, platform: 0.9, leap_cli: 1.9}
```

Shortly after the deploy, the overall servers memory consumption went up.
From [dev1 memory graph](https://unstable.pixelated-project.org/pnp4nagios/index.php/graph?host=dev1.dev.pixelated-project.i&srv=Memory_used&start=1474290737&end=1474315937):

![image](https://cloud.githubusercontent.com/assets/488213/18706020/7f8d26f6-7ff0-11e6-8c8b-cd5f02cb45d3.png)

**Comment by varac** [comment] 2016-09-21 09:46
@thaissiqueira could you pls tell what commit of the `pixelated-platform-environments` you used for deploying ?

**Comment by thaissiqueira** [comment] 2016-09-21 22:36
@varac my last commit is e661bfaab441baf965189b3e5336d1f8c3fdc818

**Comment by rdevries-thoughtworks** [comment] 2016-09-22 09:41
As of commit ad1d33a8, if you run the user agent with the `--manhole` option, it will listen on port 8008 for telnet connections, and on 8009 for ssh connections. You can login with user `pix` and no password. This will give you an interactive python shell, which I used for heap snapshots using `guppy`. A *relatively* good intro you can find [here](http://smira.ru/wp-content/uploads/2011/08/heapy.html). But to get you started, you can paste the following in the shell once per session to set things up:

```python
from guppy import hpy
hp = hpy()
hp.setrelheap()  # to make heap snapshots relative to the current situation
hs = []
```

And then every now and then:

```python
hs.append(hp.heap())  # append a heap snapshot
hs[-1]  # print it (in a table, only first 10 rows)
_.more  # print the next 10 rows (NB: _ refers to the result of the last statement)
```

**NB: don't expose this port to the outside world, you can basically do anything in that python shell.**

**Comment by mnandri** [comment] 2016-09-22 09:55
I just restarted dev and saw some things that need reviews:

For some reason, the file `loglinegenerator.py` didn't get packaged and on dev it throws this error:
```
2016-09-22T11:28:34.139205+02:00 dev1 pixelated-user-agent[19983]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/application.py", line 44, in <module>
2016-09-22T11:28:34.139280+02:00 dev1 pixelated-user-agent[19983]: from loglinegenerator import ILogLineGenerator
2016-09-22T11:28:34.139370+02:00 dev1 pixelated-user-agent[19983]: ImportError: No module named loglinegenerator
```

Also,
the twisted plugin folder doesn't have the "right" permission for the user `pixelated` to write. We get the following log
```
2016-09-22T11:33:39.106953+02:00 dev1 pixelated-user-agent[21108]: 2016-09-22 09:33:39 [twisted] INFO Unable to write to plugin cache /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/plugins/dropin.cache:
2016-09-22T11:33:40.110611+02:00 dev1 pixelated-user-agent[21108]: 2016-09-22 09:33:40 [twisted] INFO Unable to write to plugin cache /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/plugins/dropin.cache:
2016-09-22T11:33:41.114199+02:00 dev1 pixelated-user-agent[21108]: 2016-09-22 09:33:41 [twisted] INFO Unable to write to plugin cache /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/plugins/dropin.cache:
2016-09-22T11:33:42.108516+02:00 dev1 pixelated-user-agent[21108]: 2016-09-22 09:33:42 [twisted] INFO Unable to write to plugin cache /usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/plugins/dropin.cache:
```
either we change the plugins folder permission or we restore root as the pixelated-server user.

**Comment by rdevries-thoughtworks** [comment] 2016-09-27 21:22
We verified that the functional tests logout all the users that it logs in, so it doesn't introduce leaks by leaving sessions open.

**Comment by bwagnerr** [comment] 2016-09-28 14:00
**So, considering leap was not seeing the memory leak and we have few parts, we are going to start stressing some parts of the application piece by piece to try to nail down further the problem and make it more reproduceable (outside of a production environment), we'll start by investigating the mail indexer because that's the biggest difference between bitmask and pixelated ua.

**Comment by rdevries-thoughtworks** [comment] 2016-09-30 21:50
We've found someting interesting, of which we're not sure it's *the* leak, but it seems worth mentioning here:

On creation of `SQLCipherU1DBSync`, the `finalClose` method is registered to be called from the reactor only on shutdown. This means that even if we delete the other references to SQLCipher when a user logs out, the reactor will still hold a reference to them until the user agent is stopped.

This means one new `SQLCipherU1DBSync` is created on every user login, which is never destroyed. This object holds references to e.g. `SoledadCrypto` and `SQLCipherConnectionPool`.

**Comment by rdevries-thoughtworks** [comment] 2016-09-30 22:16
We removed the reference of `SQLCipherU1DBSync` (not a proper fix, just searching for the next leak).

After that, these are the last measurements with three logins followed by three logouts.

<details>
  <summary>Click to expand measurements</summary>
```python
(Pdb) objgraph.show_growth()
function                      17577    +17577
dict                          10159    +10159
tuple                          8845     +8845
list                           4843     +4843
weakref                        4691     +4691
builtin_function_or_method     2445     +2445
type                           2194     +2194
getset_descriptor              2062     +2062
wrapper_descriptor             1448     +1448
set                            1275     +1275

(Pdb) objgraph.show_growth()
function                      18252      +675
dict                          10543      +384
tuple                          9088      +243
list                           4984      +141
weakref                        4805      +114
type                           2274       +80
builtin_function_or_method     2509       +64
getset_descriptor              2123       +61
instancemethod                  260       +40
cell                            700       +36

(Pdb) objgraph.show_growth()
StringifiableFromEvent            34       +12
HTTPChannel                        5        +1
Server                             5        +1
_GenericHTTPChannelProtocol        5        +1
Logger                            76        +1

(Pdb) objgraph.show_growth()
dict                          10674      +131
tuple                          9159       +71
StringifiableFromEvent           61       +27
cell                            706        +6
builtin_function_or_method     2515        +6
Logger                           81        +5
weakref                        4809        +4
function                      18255        +3
BufferFile                        4        +3
_HTTP11ClientFactory              6        +3

(Pdb) objgraph.show_growth()
StringifiableFromEvent            75       +14
HTTPChannel                        6        +1
Server                             6        +1
_GenericHTTPChannelProtocol        6        +1
Logger                            82        +1

(Pdb) objgraph.show_growth()
dict                          10798      +124
StringifiableFromEvent           97       +22
tuple                          9171       +12
cell                            712        +6
builtin_function_or_method     2521        +6
Logger                           87        +5
function                      18258        +3
_HTTP11ClientFactory              9        +3
list                           4988        +2
_socketobject                     8        +1
```
</details>

We'll go deeper into these  going forward.

**Comment by tuliocasagrande** [comment] 2016-10-04 20:46
We found the following leak today:

* `LimitedHistoryLogObserver` (and `StringifiableFromEvent` internally):
    - It's created by twisted and **store** received loglines for the proper logger later;
    - If a logger is not started, it is going to grow up to 65536 loglines;
    - We only have a python logger on Pixelated;
    - **Solution:** we should move our logging to use twisted logger and call `globalLogBeginner.beginLoggingTo` explicitly

**Comment by tuliocasagrande** [comment] 2016-10-04 20:47
We also found a leak of whoosh file buffers. We still need to understand it better.

* Whoosh database file (`Server`, `Reader` and `BufferFile` internally):
    - Apparently we're not closing whoosh's `BufferFile` properly

**Comment by bwagnerr** [comment] 2016-10-07 13:28
Quick update:

I created the following issues to follow up:
- Issue https://github.com/pixelated/project-issues/issues/358 to track the PR on Soledad
- Issue https://github.com/pixelated/pixelated-user-agent/issues/789 for getting rid of the old Twisted logger and fix the leak of TemporaryLogObserver
- Issue https://github.com/pixelated/pixelated-user-agent/issues/790 to work on the whoosh leak of FileBuffers and Database

I'll close this issue and we'll work on the specific ones.

**Closed by bwagnerr** 2016-10-07 13:28 UTC
Labels: 2 - Development, Memory Leak
