### ISSUE TITLE
LEAP email delivery test are failing

### ISSUE THREAD

**Issue by re-nobre** [pixelated/pixelated-user-agent#788] opened 2016-10-03 17:34 UTC
## What

Someone was installing a Pixelated provider following [these instructions](https://github.com/pixelated/puppet-pixelated#manual-installation) and ran the LEAP tests to make sure that the installation was ok. But the installation was ok and the LEAP tests failed. 
The tests failed because one of the tests tries to create an user to send an email and the username that the test tried to create was already taken.
## Definition of done

TBD

**Comment by varac** [comment] 2016-10-04 10:15
This is the output of `leap test` atm:

```
 = [xxxdnn3347.midiapopular.org.br] PASS: Network > Can connect to internet?
 = [xxxdnn3347.midiapopular.org.br] PASS: Network > Is stunnel running?
 = [xxxdnn3347.midiapopular.org.br] PASS: Network > Is shorewall running?
 = [xxxdnn3347.midiapopular.org.br] PASS: Network > Are server certificates valid?
 = [xxxdnn3347.midiapopular.org.br] PASS: CouchDB > Are daemons running?
 = [xxxdnn3347.midiapopular.org.br] PASS: CouchDB > Is CouchDB running?
 = [xxxdnn3347.midiapopular.org.br] PASS: CouchDB > Do ACL users exist?
 = [xxxdnn3347.midiapopular.org.br] PASS: CouchDB > Do required databases exist?
 = [xxxdnn3347.midiapopular.org.br] PASS: CouchDB > Can records be created?
 = [xxxdnn3347.midiapopular.org.br] PASS: Webapp > Can contact couchdb?
 = [xxxdnn3347.midiapopular.org.br] PASS: Webapp > Can contact couchdb via haproxy?
 = [xxxdnn3347.midiapopular.org.br] PASS: Webapp > Are daemons running?
 = [xxxdnn3347.midiapopular.org.br] PASS: Webapp > Can access webapp?
 = [xxxdnn3347.midiapopular.org.br] PASS: Webapp > Can create and authenticate and delete user via API?
 = [xxxdnn3347.midiapopular.org.br] PASS: Webapp > Can sync Soledad?
 = [xxxdnn3347.midiapopular.org.br] PASS: Mx > Can contact couchdb?
 = [xxxdnn3347.midiapopular.org.br] PASS: Mx > Can contact couchdb via haproxy?
 = [xxxdnn3347.midiapopular.org.br] PASS: Mx > Can query identities db?
 = [xxxdnn3347.midiapopular.org.br] PASS: Mx > Are MX daemons running?
 = [xxxdnn3347.midiapopular.org.br] FAIL: Mx > Can deliver email? [mx.rb:106]:
 = [xxxdnn3347.midiapopular.org.br]   Expected success code from POST https://api.midiapopular.org.br:4430/1/users.json, but got 422 instead.
 = [xxxdnn3347.midiapopular.org.br]   {"errors":{"login":["has already been taken"]}}
 = [xxxdnn3347.midiapopular.org.br] Tests halted on failure (because of --no-continue).
 = bailing out
```

**Comment by varac** [comment] 2016-10-04 11:55
I wrote back:

```
...
the test is fixed in latest leap_platform develop branch, which will be
released as 0.9 soon (see my last mail).
The regarding issue is here: https://leap.se/code/issues/8035

Pls ignore this test until you can upgrade to 0.9.
...
```

**Comment by tuliocasagrande** [comment] 2016-10-04 12:48
@varac 
I saw you last mail. Do you think we should close this issue for now?

**Comment by varac** [comment] 2016-10-04 13:58
not yet, i'm waiting for a confirmation

**Comment by varac** [comment] 2016-10-04 14:33
@re-nobre everything server-related should be in puppet-pixelated imo

**Comment by varac** [comment] 2016-10-04 14:34
@tuliocasagrande damn, the issue still persists even after using leap_platform:develop. weird.

**Comment by varac** [comment] 2016-10-04 15:06
@rdevries-thoughtworks  see https://leap.se/code/issues/8035#note-7

**Comment by rdevries-thoughtworks** [comment] 2016-10-04 17:02
@elijh is investigating, so we'll put this on hold for now.

**Comment by varac** [comment] 2016-10-06 16:43
I talked with elijah he said that this might be an out-of-sync issue between the `users` and `identities` table for the mail test-user (`test_user_email`). So maybe this user exists in the users db but not in the identities or vice versa.
We could try to reproduce this on one of our envs by removing the user from only one of those dbs and see if the test fail.

**Comment by elijh** [comment] 2016-10-06 20:06
I think that deleting the user test_user_email in the web admin should do the trick. The bug, to the extent that there is one, appears to be that the tests assume that the user record does not exist if the corresponding identity record also does not exist. This is normally a good assumption, unless something has gone wrong.

**Comment by varac** [comment] 2016-10-10 13:56
@elijh I checked and `test_user_email` is present in both `users` and `identities`.
Wouldn't deleting the user using the webapp block the account and you need to [manually remove the entry from the identities db](https://leap.se/en/docs/platform/services/couchdb#re-enabling-blocked-account) ?

**Comment by deniscostadsc** [comment] 2016-10-10 18:18
@varac, where the test code is stored? I tried to take a look in the code but I couldn't find it.

> I think that deleting the user test_user_email in the web admin should do the trick.

@elijh, how can I do that? If you send me the test In can try fix it and send a PR.

**Comment by varac** [comment] 2016-10-10 19:24
@deniscostadsc It at `leap_platform/tests/server-tests/white-box/mx.rb`. Deleting a user is done by logging into the webapp with admin privileges, searching for the user in the `users` tab, and clicking on `destroy my account`.

**Comment by elijh** [comment] 2016-10-10 19:59
As you note, destroying the users keeps the username reserved, for security reasons. To unreserve the username, you have to search for the username under the 'usernames' tab. In the future, there will be an admin option to do this in one step.

The thing that I am puzzled by is why the query of couchdb for the identity test_user_email is failing. That is surprising.

The query is:

    api_url("/identities/#{URI.encode(address)}.json")

The next step would be to add some log statements to the webapp and then tail /var/log/leap/webapp.log. I could do this, if I could reproduce it.

**Comment by elijh** [comment] 2016-10-10 19:59
I should have said, query the webapp API. It is not hitting the couchdb directly.

**Comment by deniscostadsc** [comment] 2016-10-10 20:48
If the solution is to remove the users after the test, we should maybe wait unit @thaissiqueira and @tayanefernandes finish #787.

**Comment by elijh** [comment] 2016-10-11 04:27
is this a reproducible error? I mean, if the db is reset by deleting the test user, does this error message ever show up again?

**Comment by varac** [comment] 2016-10-12 09:20
@deniscostadsc why should we wait - we introduce a new blocker here.
Removing the test user is a very easy task for the provider.
Is this the reason why it's still tagged 'blocked' ?

**Comment by deniscostadsc** [comment] 2016-10-19 18:52
I put blocked because @tayanefernandes and @thaissiqueira were working in a way to remove user programmatically. As soon as they finish the task we can maybe reuse what they did here. Remeber that we have to do that on araguaia, to fix the test there, so we can run one script to fix both problems.

**Comment by thaissiqueira** [comment] 2016-10-24 17:59
The task that @tayanefernandes and I did will not fix this problem.

> I think that deleting the user test_user_email in the web admin should do the trick.

We ran ```leap test``` in an environment with 'test_user_email' and even with this user in there the test was ok.

I'll check if the problem persists on Araguaia's  environment.

**Comment by thaissiqueira** [comment] 2016-10-25 13:03
Yes, the test still breaks on Araguaia's environment.

@varac , do you know how can we reproduce this error?

**Comment by varac** [comment] 2016-10-26 10:06
@thaissiqueira I really don't know how to reproduce the error, Araguaia is the first provider that stepped into this problem. 

> Removing the test user is a very easy task for the provider.

Did we already asked them to do this ? The fact that the test succeeds for us with the `test_user_email` present doesn't mean that removing it on their side will not fix it (sorry for the multiple negation here :D)

Asking them if we could have (temporary) access to their instance might help a lot to debug it.

**Comment by thaissiqueira** [comment] 2016-11-06 15:03
> Asking them if we could have (temporary) access to their instance might help a lot to debug it.

I'm not sure if ask for access is a good idea even temporary because we'll loose some of the sysadmin user feedback.

**Comment by thaissiqueira** [comment] 2016-11-06 15:05
Since last installation this test is not breaking anymore.
Make sense for you close this issue for now and reopen it if necessary?

**Comment by varac** [comment] 2016-11-06 15:41
thx @thaissiqueira, closing for now

**Closed by varac** 2016-11-06 15:41 UTC
Labels: Araguaia, bug, LEAP
