### ISSUE TITLE
Sync takes long time

### ISSUE THREAD

**Issue by ayoyoness** [pixelated/pixelated-user-agent#638] opened 2016-03-07 10:46 UTC
To reproduce:
- send yourself a message from the same provider or other providers
- wait for email sent acknowledgement or check email is in sent folder/tag
- go back to inbox
- click the refresh button
- No new email

**Comment by re-nobre** [comment] 2016-06-13 11:39
I tested in my account and happened the same situation.
Then I tried to refresh all the browser window (clicking the browser refresh button) and the message also didn't appear. 

So, I think that it's not a problem with the refresh botton. Maybe the problem it's the time that the server takes to delivery an email.

Is it make sense?

**Comment by mnandri** [comment] 2016-06-14 15:44
I agree... could be related to soledad sync... especially given the fact that if you send an email to an external account, the email will be received fairly quickly...
so yes, improvement/optimisation required... but not a bug per-se...

**Comment by bwagnerr** [comment] 2016-06-16 15:41
This is not a bug, but the delay happens because of the receiving not the sending. The mail has to pass through a lot of hoops before it gets back to you (server pickup, sync, decrypt pool) the worst case of the loops can take 45 seconds not considering network..

**Comment by re-nobre** [comment] 2016-06-16 16:07
yeah, @bwagnerr !
Because of that we removed the bug label.

About the time, the last time that I tested take more than 2 minutes. 
So, I think we can keep the issue, right?

**Comment by bwagnerr** [comment] 2016-06-16 16:25
@re-nobre I don't think it is productive, the only way to make it better is to improve soledad, leap mx and leap mail, unfortunately there is nothing we can do on this side

**Comment by varac** [comment] 2016-06-17 08:31
> the only way to make it better is to improve soledad, leap mx and leap mail, unfortunately there is nothing we can do on this side

If there's room for improvement in soledad, leap mx and leap mail, we can contribute to those components right? or what do you mean with "nothing we can do on this side" ?

**Comment by bwagnerr** [comment] 2016-06-17 13:59
@varac Sorry if I was not clear enough. There's always room for improvements everywhere, but there's not a simple task or issue that we could do to improve this.

Fot example, for now leap mail only initiates a sync every 60 seconds, but for a mail to sync, it has to be picked up by leap mx on the server first (that runs every 15 seconds), but the sync itself can take a while depending on the number of documents (at least 5 seconds). If you get on the bad side of the counting, it can take more than 1 minute to go through all this process.

The thing is that these were architectural decisions, the timing and the fact that we do polling almost everywhere, so to change this, we would need to sit down, discuss architecture and propose improvements, together with leap folks. Considering the other problems we're having, I would gladly have this kinda slow than the floating point exception or the ui problems, this could be amended with user feedback until we get ready to tackle it, but I don't think this issue helps with that or will be of use when it gets to the time we tackle this, because it is a compound problem (more like a goal, less like an issue).

That is why I would prefer we close it :)

**Comment by felixhammerl** [comment] 2016-06-29 10:11
Further information:

* [Build Toolchain](https://github.com/pixelated/pixelated-user-agent/wiki/Build-Toolchain)
* [JS Architecture](https://github.com/pixelated/pixelated-user-agent/wiki/JS-Architecture)
* [SOLEDAD](https://github.com/pixelated/pixelated-user-agent/wiki/SOLEDAD:-Synchronization-of-Locally-Encrypted-Documents-Among-Devices)

**Comment by anikarni** [comment] 2017-01-20 13:43
Closing this issue as this is a constant discussion and should be reopened if we find specific points for further improvement.

**Closed by anikarni** 2017-01-20 13:43 UTC
Labels: LEAP, Soledad
