### ISSUE TITLE
Removing main blocker

### ISSUE THREAD

**Issue by tuliocasagrande** [pixelated/pixelated-user-agent#759] opened 2016-08-16 14:38 UTC
As pointed by @olabini, we have at least one really good candidate that is blocking the sync:

[_get_leap_session in service/pixelated/resources/auth.py](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/resources/auth.py#L58)

It's blocking the main reactor thread for about 4 seconds.

**Comment by mnandri** [comment] 2016-08-16 17:21
We had a look at the [blocking reactor commits](https://github.com/pixelated/pixelated-user-agent/commit/e882e1f4dba1ca6459fc527cd674a4a965434905)
The approach tried in the commits might not prove being fruitful. Simply because one cannot use a defer.inlineCallbacks on an already a Defer.addCallback

We advocate trying to investigate directly what is blocking on LeapSessionFactory.create. Since, it is already blocking within than method. Pushed on the branch [get_leap_session](https://github.com/pixelated/pixelated-user-agent/commit/a8d2ecf822cd4a4476cb175e35c8a2de70e8bc1d)
we obtain something like this:
```
# cat ~/MetricsTime | grep haha | sort
Unknown 0.00001 haha!!! create smtpinfo
Unknown 0.00002 haha!!! auth and account email
Unknown 0.00002 haha!!! create leap mail store
Unknown 0.00007 haha!!! create leap dir
Unknown 0.00008 haha!!! create database dir
Unknown 0.00081 haha!!! download smtp cert
Unknown 0.01352 haha!!! create nicknym
Unknown 0.02553 haha!!! download smtp info
Unknown 0.02991 haha!!! download certificate
Unknown 0.28148 haha!!! create soledad
```
The corresponding _get_leap_session_time is `0.36199`
It is pretty clear that creating the soledad instance is the biggest culprit.

There are a couple of things we could do here:
- all the http calls at this point looks like they are static (as in does not have to be downloaded every time for all the users)... and even if downloaded, could be done async using twisted or deferToThread
- deferToThread the soledad instantiation or better yet, dive into the constructor and see what is taking this much time in there (probably the extra threadpool creation,, but just a guess). Investigate ways to make that async.
- nicknym instantiation, as a lesser priority though.

**Comment by mnandri** [comment] 2016-08-17 08:00
We have confirmed, moving soledad instatiation to a thread changes the order of reactor blocking callbacks. See code [here](https://github.com/pixelated/pixelated-user-agent/commit/d1ee3559d7648aa5182d09d83b1e48e9c0003ea9).

With one user, we obtain:
```
0.06296 EXECUTING <function do_the_rest_on_main_thread at 0x7efe9dfbd848> (/root/junk/pixelated-user-agent/service/pixelated/bitmask_libraries/session.py:266) in thread 139632611260160 deferred 139632037547688
0.10575 EXECUTING <bound method _ThreePhaseEvent._continueFiring of <twisted.internet.base._ThreePhaseEvent object at 0x7efeba31fed0>> (/root/junk/venv/local/lib/python2.7/site-packages/twisted/internet/base.py:420) in thread 1396326112
0.22459 EXECUTING ><generator object _index_all_mails at 0x7efe9c6b36e0> in thread 139632611260160 deferred 139632010832856  -- 0.22462 EXECUTING <function gotResult at 0x7efe9c6b6b18> (/root/junk/venv/local/lib/python2.7/site-packages/
0.22523 EXECUTING ><generator object all_mails at 0x7efe9c640410> in thread 139632611260160 deferred 139632010831488  -- 0.22525 EXECUTING <function gotResult at 0x7efe9c6b6a28> (/root/junk/venv/local/lib/python2.7/site-packages/twisted
0.22587 EXECUTING ><generator object all_mails at 0x7efe9c640460> in thread 139632611260160 deferred 139632010832496  -- 0.22589 EXECUTING <function gotResult at 0x7efe9c680848> (/root/junk/venv/local/lib/python2.7/site-packages/twisted
0.22653 EXECUTING ><generator object get_mails at 0x7efe9c6405f0> in thread 139632611260160 deferred 1392016-08-17 09:37:24 [leap.soledad.client.sync] DEBUG Soledad target sync info:
0.22826 EXECUTING <bound method DeferredList._cbDeferred of <DeferredList at 0x7efe9c64b098>> (/root/junk/venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:881) in thread 139632611260160 deferred 139632010896808
0.22923 EXECUTING ><generator object get_mail at 0x7efe9c640690> in thread 139632611260160 deferred 139632010896808  -- 0.22925 EXECUTING <function gotResult at 0x7efe9c6b6aa0> (/root/junk/venv/local/lib/python2.7/site-packages/twisted/
0.22995 EXECUTING ><generator object _leap_message_to_leap_mail at 0x7efe9c640dc0> in thread 139632611260160 deferred 139632010637824  -- 0.22998 EXECUTING <function gotResult at 0x7efe9c6b6e60> (/root/junk/venv/local/lib/python2.7/site
0.23065 EXECUTING ><generator object _mailbox_name_from_uuid at 0x7efe9c640f00> in thread 139632611260160 deferred 139632010639192  -- 0.23067 EXECUTING <function gotResult at 0x7efe9c6b6938> (/root/junk/venv/local/lib/python2.7/site-pa
0.23133 EXECUTING ><generator object _mailbox_uuid_to_name_map at 0x7efe9c640e60> in thread 139632611260160 deferred 139632010639120  -- 0.23135 EXECUTING <function gotResult at 0x7efe9c680230> (/root/junk/venv/local/lib/python2.7/site-
```
the function `do_the_rest_on_main_thread` now takes the smallest (still noticeable) time.

As expected, the same metrics are observed. With just, the soledad instatiation run on a separate thread.
```
Unknown 0.00001 haha!!! create smtpinfo
Unknown 0.00002 haha!!! auth and account email
Unknown 0.00002 haha!!! create leap mail store
Unknown 0.00009 haha!!! create database dir
Unknown 0.00009 haha!!! create leap dir
Unknown 0.00217 haha!!! download smtp cert
Unknown 0.02295 haha!!! download smtp info
Unknown 0.02855 haha!!! download certificate
Unknown 0.03724 haha!!! create nicknym
Unknown 0.28522 haha!!! create soledad
```
The next step is to go down from the soledad instatiation and figure out what is taking time there.

**Comment by mnandri** [comment] 2016-08-17 08:33
with this [solead.patch](https://gist.github.com/mnandri/39849f1f3c91ad0911443764a3431c75), we obtain
```
# cat ~/MetricsTime | grep hehe | sort
Unknown 0.00002 hehe!!! instantiate soledad crypto
Unknown 0.00003 hehe!!! add private attributes
Unknown 0.00004 hehe!!! set token
Unknown 0.00006 hehe!!! init config with defaults
Unknown 0.00020 hehe!!! init working dir
Unknown 0.00025 hehe!!! init shared db
Unknown 0.01087 hehe!!! init u1db syncer
Unknown 0.08513 hehe!!! init secrets
Unknown 0.23489 hehe!!! init u1db sqlcipher backend
```
Main culprit: `_init_u1db_sqlcipher_backend`, to investigate : `_init_secrets` and `_init_u1db_syncer`

**Comment by mnandri** [comment] 2016-08-17 09:05
with this [soledad.patch](https://gist.github.com/mnandri/1ac854bac14b5ff5e30c363c084e79cd), we obtain

```
# cat ~/MetricsTime | grep hoho | sort
Unknown 0.00003 hoho!!! get sqlcipher options
Unknown 0.00099 hoho!!! init sync db
Unknown 0.01123 hoho!!! get connection pool
Unknown 0.16100 hoho!!! get key and sync_db_key
```
Main culprit: get key/sync_db_key

**Comment by mnandri** [comment] 2016-08-17 10:08
We found the culprit for `u1db sqlcipher backend` is scrypt.hash
found in https://github.com/pixelated/soledad/blob/develop/client/src/leap/soledad/client/api.py#L291-L292

**Comment by olabini** [comment] 2016-08-17 12:15
Wow, does it call scrypt 3 times - is it with the same arguments? Anyway, it makes complete sense that scrypt takes a lot of time. It is actually meant to. This is a perfect example of something that should be offloaded into a different process actually.

**Comment by rdevries-thoughtworks** [comment] 2016-08-17 12:30
Both calls from `_init_u1db_sqlcipher_backend` use the same password but a different salt. The call from `_init_secrets` uses a different password.

**Comment by olabini** [comment] 2016-08-17 13:20
Interesting. Well, it might be worth writing a small spike seeing how python impacts scrypt, since it's on purpose a memory intensive operation that could block the whole process. I think farming out the scrypt operation to a separate process is a good idea actually.

**Comment by bwagnerr** [comment] 2016-08-18 17:59
Hey, we picked this up again after @mnandri and @rdevries-thoughtworks tried to dig deeper on the problem. We made the following change https://github.com/pixelated/pixelated-user-agent/commit/0b4e996bd0aeb330eca6d33140980a59e501b653 so that the user bootstrap process is independent from the user authentication. This way we can offload the entire user bootstrap to that it doesn't affect the other users

**Comment by olabini** [comment] 2016-08-18 18:11
I don't understand this at all. You are still creating the leap session in the main reactor thread, so it will still block, right?

**Comment by bwagnerr** [comment] 2016-08-18 18:32
In this first step yes, so it doesn't help by itself. The difference is that now we can offload everything after the authentication (setup of leap session, of the user services) to another process/thread so it won't block the reactor anymore, does that make sense?

**Comment by olabini** [comment] 2016-08-18 18:39
No, not necessarily. That depends on what is taking the time. If it's an http request for example, it makes no sense offloading it to process/thread.

**Comment by bwagnerr** [comment] 2016-08-18 19:15
The problems were identified in a previous comment by @mnandri to be on scrypt.hash calls, considering the nature of those calls, it makes sense to offload those to a different process

**Comment by rdevries-thoughtworks** [comment] 2016-08-19 12:07
A few open questions:

- which portion of the code should we offload to a subprocess? Just the call to `scrypt.hash` or everything inside `leap.soledad.client`, or are there other nice boundaries?
- what type of subprocess to use? Ampoule, txpool or bare twisted `spawnProcess`? And in the latter case, should we limit the number of processes, and do we want to spawn a process for every invocation?

Some measurements (on my laptop):

- an `scrypt.hash` call takes ~0.05s
- a call to spawnProcess takes ~0.001s

**Comment by bwagnerr** [comment] 2016-08-19 12:53
I like the txpool idea and considering soledad has more than one of those calls I would create one shared pool for all soledad instances on soledad initialization

**Comment by olabini** [comment] 2016-08-19 13:15
I disagree. I would prefer putting just the scrypt.hash operation into a separate process. In fact, I don't even think it should be a python process if not necessary. Since scrypt is a purely functional operation, spawning a process and getting the result the easiest way possible seems like a good idea. I would also argue that not using a process pool is a good idea, since that allows us to use as many scrypt calls as the OS allows. Finally, the extra cost of spawnProcess is not enough to add any significant cost to the scrypt call, so I would say use that.

**Comment by rdevries-thoughtworks** [comment] 2016-08-19 13:48
We had a short discussion, and came up with the same actually. We can leave any optimization (process pools / persistent processes) till the point that we might need it (if ever).

**Comment by bwagnerr** [comment] 2016-08-19 14:40
@olabini the scrypt command line utility only accepts passwords interactively, we'll try using a python process

**Comment by bwagnerr** [comment] 2016-08-20 01:05
Updating:
We tried the twisted spawnProcess and hit the following predictable problem:
spawnProcess will give us a deferred, but soledad initialization is purely synchronous, so we would have to bubble up all the way to LeapSessionFactory create in order to get any meaningful result with that approach now.

After that I started going the other way around and try to split up the initialization of the LeapSession into smaller deferred chunks and converting the code from outside in.

With these latest changes on the branch above I got these numbers:

Users | Number of big calls | Average time of the calls
1 user | 2 gotResults | ~1 sec 
2 users | 4 gotResults | ~1-2 secs
5 users | 10 gotResults | 0.5-2.5 secs

I also manage to move two http calls that weren't user specific from the login to the user agent bootstrap.

So next we have two obvious improvements
- Dig into what those gotResult calls are (up on this issue Naval mentioned a way of identifying them) and split them/offload them if necessary
- Make the initialization async even deeper so that we can defer to thread/processes only the parts that are really needed (scrypt hash, http calls, file opens)

**Comment by rdevries-thoughtworks** [comment] 2016-08-20 11:07
What I understand currently of `gotResult`:

When you have an `@inlineCallback` with `yield` expressions, the `yield` hands control over to twisted. Twisted then puts some placeholder callback on the reactor, and when that placeholder is picked up from the reactor, `gotResult` gives control back to the `@inlineCallback` generator with the result from the yield expression. `gotResult` has access to the `@inlineCallback` generator function name through (if I recall correctly) a closure variable, I think it was called `g`. So `g.__name__` should give you the name of the `@inlineCallback`.

Please double check, because I just dump this from the top of my head...

**Comment by thaissiqueira** [comment] 2016-08-22 18:53
We adapted twisted patch to show `inlineCallback` function names and then we applied it on vagrant and we got this output:

```
EXECUTING <generator object _create_new_session at 0x7f37e80f6780> in thread 139878325012224 1.28108
EXECUTING <generator object setup_keymanager at 0x7f37e80f6c80> in thread 139878325012224 1.28155
EXECUTING <generator object _index_all_mails at 0x7f37c870cdc0> in thread 139878325012224 0.89664
EXECUTING <generator object all_mails at 0x7f37c870cf50> in thread 139878325012224 0.89748
EXECUTING <generator object all_mails at 0x7f37c8728050> in thread 139878325012224 0.89799
EXECUTING <generator object get_mails at 0x7f37e80f6280> in thread 139878325012224 0.89867
EXECUTING <bound method DeferredList._cbDeferred of <DeferredList at 0x7f37c85e73f8>> (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:883) in thread 139878325012224 0.89949
EXECUTING <generator object get_mail at 0x7f37c85e41e0> in thread 139878325012224 0.90064
EXECUTING <generator object _leap_message_to_leap_mail at 0x7f37c85dd2d0> in thread 139878325012224 0.90127
EXECUTING <generator object _mailbox_name_from_uuid at 0x7f37c85c7f00> in thread 139878325012224 0.90197
EXECUTING <generator object _mailbox_uuid_to_name_map at 0x7f37c85c7af0> in thread 139878325012224 0.90267
EXECUTING <bound method DeferredResource._cbChild of <twisted.web.util.DeferredResource instance at 0x7f37ecdc19e0>> (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/web/util.py:143) in thread 139878325012224 0.10171
```

**Comment by thaissiqueira** [comment] 2016-08-22 20:00
We sorted by time and clean up the output:


setup_keymanager **2.89611**
_create_new_session **2.89561**
_mailbox_uuid_to_name_map **0.21703**
_mailbox_name_from_uuid **0.21654**
_leap_message_to_leap_mail **0.21564**
get_mail **0.21449**
DeferredList._cbDeferred **0.21217**
get_mails **0.21106**
all_mails **0.21013**
all_mails **0.20927**
_index_all_mails **0.20791**

**Comment by olabini** [comment] 2016-08-22 21:20
Just to clarify, EACH one of those timings is independent from the other times, and they are all running on the reactor main thread?

**Comment by bwagnerr** [comment] 2016-08-22 22:19
@olabini They are all running on the main reactor thread, as you can check from the raw output above.
We still didn't check if they are wholly independent, as we just managed to identify them

**Comment by olabini** [comment] 2016-08-23 00:59
Yes well. I see they are running on the _same_ thread. There is nothing that says it is the main reactor thread.

**Comment by thaissiqueira** [comment] 2016-08-23 15:03
To make sure that those methods are running on the main thread we identified the main thread by putting a print on the application.py [application.py](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/application.py#L101) file:

```
def initialize():
    log.info('Starting the Pixelated user agent')
    args = arguments.parse_user_agent_args()
    logger.init(debug=args.debug)
    services_factory = _create_service_factory(args)
    resource = RootResource(services_factory)

    def start():
        start_async = _start_mode(args, resource, services_factory)
        add_top_level_system_callbacks(start_async, services_factory)

---->    print('The main thread is ' + str(threading.current_thread().ident))
    log.info('Running the reactor')
    reactor.callWhenRunning(start)
    reactor.run()
```

Then we checked that those methods are running with the same thread ID mapped as the main thread.

> The main thread is **140044645365504**
> 2016-08-23 14:30:25 [pixelated.application] INFO Running the reactor
> 2016-08-23 14:30:33 [pixelated.application] INFO Starting the API on port 3333
> EXECUTING <bound method _ThreePhaseEvent._continueFiring of <twisted.internet.base._ThreePhaseEvent object at 0x7f5ea9593b50>> (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/base.py:420) in thread 140044645365504 7.75462
> EXECUTING <generator object _create_new_session at 0x7f5e94fbc550> in thread **140044645365504** 1.23947
> EXECUTING <generator object setup_keymanager at 0x7f5e94fbca50> in thread **140044645365504** 1.24050
> EXECUTING <generator object _index_all_mails at 0x7f5e94fbc050> in thread 140044645365504 0.23502
> EXECUTING <generator object all_mails at 0x7f5e94688c30> in thread 140044645365504 0.23580
> EXECUTING <generator object all_mails at 0x7f5e94688be0> in thread 140044645365504 0.23643
> EXECUTING <generator object get_mails at 0x7f5e94688e10> in thread 140044645365504 0.23714
> EXECUTING <bound method DeferredList._cbDeferred of <DeferredList at 0x7f5e94698ea8>> (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:883) in thread 140044645365504 0.23790
> EXECUTING <generator object get_mail at 0x7f5e94688dc0> in thread 140044645365504 0.24073
> EXECUTING <generator object _leap_message_to_leap_mail at 0x7f5e946a5410> in thread 140044645365504 0.24165
> EXECUTING <generator object _mailbox_name_from_uuid at 0x7f5e946a5500> in thread 140044645365504 0.24245
> EXECUTING <generator object _mailbox_uuid_to_name_map at 0x7f5e946a5550> in thread 140044645365504 0.24274


Because of that we assume that we are working on the main thread methods.

**Comment by olabini** [comment] 2016-08-23 15:33
OK, perfect - thank you. I think that's a reasonable assumption then ;)

**Comment by thaissiqueira** [comment] 2016-08-23 17:20
So we are closing this issue and starting the work on the two biggest main thread blockers (>1s):
- setup_keymanager #763
- _create_new_session #762

**Closed by thaissiqueira** 2016-08-23 17:20 UTC
Labels: 2 - Development

**Comment by thaissiqueira** [comment] 2016-08-23 22:30
To wrap up the issue and guide the next advancements, we measured the difference on login time before and after the split of get_leap_session, we got the following numbers:

| 1 user   | Before           | After            |
|--------|--------------|-------------|
|1st user|9.23053 secs|6.51681 secs|

| 2 users  | Before             | After             |
|---------|---------------|-------------|
|1st user  |12.96185 secs|7.76068 secs|
|2nd user|12.09043 secs|6.97641 secs|

| 5 users  | Before               | After               |
|---------|----------------|---------------|
|1st user  |23.56228 secs  |11.06628 secs |
|2nd user|24.57760 secs   |10.59770 secs|
|3rd user |15.75423 secs   |9.94912 secs  |
|4th user |16.15140 secs    |8.74547 secs  |
|5th user |16.30621 secs    |7.74715 secs  |

To get these results, we:
- Pre-created the users using the [create_users.py](https://github.com/pixelated/pixelated-user-agent/blob/master/service/test/reactor/create_users.py) script
- Added the metric detailed at the bottom of this comment
- Ran the [concurrent_logins.rb](https://github.com/pixelated/pixelated-user-agent/blob/master/service/test/reactor/concurrent_logins.rb) to login 1, 2 and 5 users
- The measurements will be on the ~/MetricsTime file.

We ran that inside a vagrant box using dev.pixelated-project.org as the provider.

**Keep in mind the user agent has to be restarted before each measurement**

------------------------------------------------

The login time we are measuring is the following on [login_resource.py](https://github.com/pixelated/pixelated-user-agent/blob/master/service/pixelated/resources/login_resource.py#L151)
```python
    @defer.inlineCallbacks
    def _handle_login(self, request):
        self.creds = self._get_creds_from(request)
        t = Clock('login')
        iface, leap_session, logout = yield self._portal.login(self.creds, None, IResource)
        t.stop()
        defer.returnValue(leap_session)
```

**Comment by olabini** [comment] 2016-08-23 23:11
This is a really great sign! It is clear there are still problems, but it's also clear you have managed to resolve the single biggest one! We are definitely on the right path here!
