### ISSUE TITLE
Find out why big accounts break permanently

### ISSUE THREAD

**Issue by giovaneliberato** [pixelated/pixelated-user-agent#560] opened 2015-12-22 13:14 UTC
##What

@albogabriel's account broke two months ago, he can't login anymore.

We tried the follow things but nothing works.
- Clearing the local files doesn't fix the problem
- Remove NGRAM doesn't make that much of a difference on the size of the index and doesn't fix the problem

The problem logs are below:

```
Traceback (most recent call last):
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/adapter/search/__init__.py", line 161, in index_mails
    self._index_mail(writer, mail)
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/whoosh/writing.py", line 197, in __exit__
    self.commit()
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/whoosh/writing.py", line 1040, in commit
    self.writer.commit(*args, **kwargs)
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/whoosh/writing.py", line 930, in commit
    finalsegments.append(self._finalize_segment())
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/whoosh/writing.py", line 869, in _finalize_segment
    self._flush_segment()
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/whoosh/writing.py", line 839, in _flush_segment
    self.fieldwriter.add_postings(self.schema, pdr, postings)
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/whoosh/codec/base.py", line 193, in add_postings
    for fieldname, btext, docnum, weight, value in items:
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/whoosh/externalsort.py", line 149, in _merge_runs
    for item in imerge(iters):
  File "/usr/lib/python2.7/heapq.py", line 376, in merge
    h_append([next(), itnum, next])
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/whoosh/externalsort.py", line 137, in _read_run
    f = self._open_run(path)
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/whoosh/writing.py", line 138, in _open_run
    return self.tempstore.open_file(path).raw_file()
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/support/encrypted_file_storage.py", line 39, in open_file
    return self._open_encrypted_file(name, onclose=self._encrypt_index_on_close(name))
  File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/pixelated_user_agent-0.1-py2.7.egg/pixelated/support/encrypted_file_storage.py", line 84, in _open_encrypted_file
    file_content = open(self._fpath(name), "rb").read()
IOError: [Errno 2] No such file or directory: '/mnt/user/search_index/mails.tmp/cwd4u8mjn3vacevlsw4hekjm6ful.run'
```

## Definition of done
@albogabriel's account works again

**Comment by fbernitt** [comment] 2016-01-13 11:02
Seems the problem is in whoosh, when it needs to merge indexes as part of its optimization process when you have a lot of stuff in it

**Comment by fbernitt** [comment] 2016-01-13 16:09
After some more investigation we are sure this is a problem with whoosh and how it behaves if the search index gets too big. 

Options are:
* Try to circumvent the problem where the underling file object is closed but the FileStruct abstraction is not in the merge_run (or provide a bug fix)
* Implement a backed (https://pythonhosted.org/Whoosh/tech/backend.html)
* Change to a different search engine

**Comment by fbernitt** [comment] 2016-01-13 16:11
(To recreate the problem we loaded 1100 mails into a new account using the pixelated-maintenance script)

**Comment by fbernitt** [comment] 2016-01-15 13:14
Accidentially closed issue instead of moving to QA

**Comment by fbernitt** [comment] 2016-01-15 13:15
To test this issue you need an account with 1000 mails or more.

**Comment by giovaneliberato** [comment] 2016-01-18 16:43
I'm trying to run `pixelated-maintenance -lc ca.crt load-mails service/test/mailsets/common` to populate the accounts, but it's not working

```
Traceback (most recent call last):
Failure: twisted.internet.defer.FirstError: FirstError[#0, [Failure instance: Traceback: <type 'exceptions.TypeError'>: expected string or buffer
/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1184:gotResult
/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/vagrant/service/pixelated/maintenance.py:150:_add_mail
/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1274:unwindGenerator
--- <exception caught here> ---
/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1128:_inlineCallbacks
/vagrant/service/pixelated/adapter/mailstore/leap_mailstore.py:198:get_mail
/vagrant/service/pixelated/adapter/mailstore/leap_mailstore.py:345:_fetch_msg_from_soledad
/home/vagrant/user-agent-venv/src/leap.mail/src/leap/mail/adaptors/soledad.py:965:get_msg_from_mdoc_id
/home/vagrant/user-agent-venv/src/leap.mail/src/leap/mail/adaptors/soledad.py:923:get_parts_doc_from_mdoc_id
/home/vagrant/user-agent-venv/lib/python2.7/re.py:181:findall
```
Have you run on this problem? @fbernitt @shyba?

**Comment by giovaneliberato** [comment] 2016-01-18 20:13
<img width="974" alt="screen shot 2016-01-18 at 6 11 18 pm" src="https://cloud.githubusercontent.com/assets/2964631/12401658/0f7d628e-be0f-11e5-8a29-6c13654aa008.png">

It works, can be launched :rocket:

**Closed** 2016-01-19 12:01 UTC
Labels: bug
