### ISSUE TITLE
Measure login time with emails

### ISSUE THREAD

**Issue by tuliocasagrande** [pixelated/pixelated-user-agent#783] opened 2016-09-14 20:29 UTC
After confirming that the **contention problem was mitigated on the login** (#771), now we need to perform tests with email synchronisation.

First, we are going to get the overall login time, using the [concurrent_logins.rb](https://github.com/pixelated/pixelated-user-agent/blob/master/service/test/reactor/concurrent_logins.rb) script.

We'll run these tests looking for reactor blockages with the twisted [defer.patch](https://github.com/pixelated/pixelated-user-agent/blob/master/service/test/reactor/defer.patch) we used before.

 After this, we intend to start instrumenting and getting metrics from inside the soledad:

* download mail
* decrypt mail
* split mail to docs
* encrypt docs
* upload docs

We thought about testing always with 10 users and then running with 1, 5, 10, 25 and 50 emails to be synced.

**Comment by tuliocasagrande** [comment] 2016-09-16 14:07
We've run the experiments by following the steps below:

- Send emails using the [send_emails_batch.sh](https://github.com/pixelated/pixelated-user-agent/blob/master/service/test/reactor/send_emails_batch.sh) script (you need to have postfix running locally)
- Wait a few minutes to ensure the emails have been processed
- Start UA
- Log in users using the [concurrent_logins.rb](https://github.com/pixelated/pixelated-user-agent/blob/master/service/test/reactor/concurrent_logins.rb)
- Stop the UA after the logins

Some concerns to keep in mind:
- When we have many emails and they take too long to download, the upload process might begin before the download ends (a new sync might be triggered after 15 seconds)

**Comment by bwagnerr** [comment] 2016-09-20 13:46
Below is the summary of the findings, I'll create graphs and get to a conclusion afterwards

---

==> 10user1email_ordered <==
10user1email

Login request 25th 4.583
Login request 75th 4.952
Login loading 25th 0.116
Login loading 75th 0.238
Login total 25th 4.797
Login total 75th 5.127

Top 10 Slowest Calls
0.3197 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139820076443392
0.3055 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139820076443392
0.2255 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139820076443392
0.2116 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139820076443392
0.2098 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139820076443392
0.2074 callback: function decrypt (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:1305) in thread 139820076443392
0.2061 inlineCallback: function decrypt (/home/vagrant/user-agent-venv/src/leap.keymanager/src/leap/keymanager/__init__.py:467) in thread 139820076443392
0.2049 inlineCallback: function decrypt (/home/vagrant/user-agent-venv/src/leap.keymanager/src/leap/keymanager/openpgp.py:598) in thread 139820076443392
0.1864 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139820076443392
0.1855 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139820076443392


==> 10user5email_ordered <==
10user5email

Login request 25th 8.447
Login request 75th 13.859
Login loading 25th 0.651
Login loading 75th 3.724
Login total 25th 11.724
Login total 75th 16.157

Top 10 Slowest Calls
0.5443 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152
0.3871 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152
0.3397 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152
0.3308 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152
0.3176 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152
0.2532 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152
0.2326 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152
0.2243 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152
0.2228 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152
0.2219 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139811347089152


==> 10user10email_ordered <==
10user10email

Login request 25th 10.873
Login request 75th 18.980
Login loading 25th 4.329
Login loading 75th 6.837
Login total 25th 17.939
Login total 75th 25.735


Top 10 Slowest Calls
0.3828 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616
0.3777 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616
0.3729 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616
0.3484 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616
0.3481 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616
0.3447 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616
0.3373 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616
0.3356 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616
0.3316 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616
0.3291 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140616224847616

==> 10user25email_ordered <==
10user25email

Login loading 25th 14.114
Login loading 75th 24.180
Login request 25th 39.892
Login request 75th 44.528
Login total 25th 63.859
Login total 75th 66.103

Top 10 Slowest Calls
0.5760 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448
0.5440 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448
0.5224 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448
0.5179 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448
0.5029 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448
0.5014 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448
0.5011 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448
0.4985 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448
0.4913 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448
0.4801 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 139635882440448


==> 10user50email_ordered <==
10user50email

Login loading 25th 20.433
Login loading 75th 153.014
Login request 25th 44.580
Login request 75th 347.143
Login total 25th 77.392
Login total 75th 379.083

Top 10 slowest calls
4.4232 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272
3.1432 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272
2.9970 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272
2.9146 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272
2.7737 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272
2.7362 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272
2.6938 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272
2.6840 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272
2.6840 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272
2.4985 callback: function _cbDeferred (/home/vagrant/user-agent-venv/local/lib/python2.7/site-packages/twisted/internet/defer.py:884) in thread 140420125206272

**Comment by bwagnerr** [comment] 2016-09-20 18:51
From these numbers, I've created graphs below for the 25th and 75th percentile of the test runs:

![graph25th](https://cloud.githubusercontent.com/assets/332069/18683496/e700b19a-7f46-11e6-9ea8-34fb470abcdf.png)
![graph75th](https://cloud.githubusercontent.com/assets/332069/18683497/e7023de4-7f46-11e6-8ae2-b7906b3f12a4.png)

This shows we have a heavy slowdown on login with emails, with heavy problems from 10 users onwards.

Considering the blocking main loop calls, these are the points we can investigate:
- There are some interestingly long decryptions of more than 200ms, even though we sent mails with less than 1k (this is more evident on the scenarios with fewer users)
- There is an unknown function that our twisted patched can't identify that dominates the slowest operations (we only detect correctly inlineCallbacks and traditional callbacks currently)
- There's an exception happening in all runs but the 50 users run.
```
[pixelated.adapter.listeners.mailbox_indexer_listener] <type 'exceptions.AttributeError'>: 'NoneType' object has no attribute 'content' /home/vagrant/user-agent-venv/src/leap.mail/src/leap/mail/adaptors/soledad.py:691
```

**Comment by thaissiqueira** [comment] 2016-09-22 22:14
As @deniscostadsc said on IRC about review statistical issues, run again the scripts to validate this issue will waste a long time to reproduce the same steps and the same results.

Given that we saw similar results on the beginning of the login time investigation, I think that for now ***we can close this issue***.

But assuming that part of solve a bug is to provide mechanisms to avoid that it will happen again, I would like to complement the list of points to investigate that @bwagnerr suggested above with a task to create a test script that aggregates all [these steps] (https://github.com/pixelated/pixelated-user-agent/issues/783#issuecomment-247609629) and giving us these 'times' as result (to put on dashboard, for example) or asserting it with some acceptable time response.

This is a typical kind of nightly test because it takes a while to finish. But it, for sure is faster than a human reproducing it.

**Comment by rdevries-thoughtworks** [comment] 2016-09-23 09:12
Maybe it's too late for this issue -- I'll leave that up to you to decide -- but my opinion is that if you have a story for e.g. investigating login times, then the outcome shouldn't be "I've seen X once", but "I structurally see X, and you can verify that if you want to". For a few reasons that come to mind immediately:

- otherwise the story can't be QA'd (NB: you might have made a mistake measuring, happens to the best)
- otherwise you won't be able to check whether a supposed is actually a fix

I understand that for statistical issues this is a bit harder to do. For those I would suggest making sure that the relevant events are logged, and using appropriate logging tools (e.g. ELK stack) anybody can see the same trends.

**Comment by thaissiqueira** [comment] 2016-09-26 20:31
@rdevries-thoughtworks I totally agree with you. 
I'm considering this issue reviewed because the result is too similar with results that we got on the firsts measurements. Only because of that I think that is not necessary to do all steps again to check the result.

Is much important keep in mind that we need do reproducible scripts to check it easier.

Because of that, in addition to the items that @bwagnerr suggested above to solve the contention problem, I'm suggesting to create a script to run all steps used to get these metrics and put it to run regularly.

Furthermore @bwagnerr suggest too:
- mesure it to understand it as a trend instead of assert some number.
- create this dashboard in a shared tool for the community be able see it too.

**Closed by thaissiqueira** 2016-09-26 20:31 UTC
Labels: 3 - Review

**Comment by mnandri** [comment] 2016-09-27 15:03
quick question:
do we know if the "exception" could hinder on the slowest call result?
as in, do we think that if we investigate and address the exception (`'exceptions.AttributeError'>: 'NoneType' object has no attribute 'content'`), would we get a different list of function for the slowest call? or it won't change (much), in which case we should totally work on identifying the `_cbDeferred` calls.

**Comment by bwagnerr** [comment] 2016-09-27 19:51
@mnandri I don't think so, because the times didn't change much on runs with or without exceptions.

**Comment by mnandri** [comment] 2016-09-28 16:52
After #784, running the login script with 10 users - 20 emails each and ignoring all `_cbDeferred` measurements, the 3 longest calls are:
- decrypt
```
0.5580 inlineCallback: function decrypt (/root/junk/git_env/src/leap.keymanager/src/leap/keymanager/__init__.py:467) in thread 139677182150400
0.5581 callback: function decrypt (/root/junk/git_env/local/lib/python2.7/site-packages/twisted/internet/defer.py:1305) in thread 139677182150400
```
- _receive_docs
```
0.1626 inlineCallback: function _receive_docs (/root/junk/git_env/src/leap.soledad.client/client/src/leap/soledad/client/http_target/fetch.py:51) in thread 139677182150400
```
- get_mails/all_mails
```
0.1571 inlineCallback: function get_mails (/root/junk/pixelated-user-agent/service/pixelated/adapter/mailstore/leap_mailstore.py:207) in thread 139677182150400
0.1573 inlineCallback: function all_mails (/root/junk/pixelated-user-agent/service/pixelated/adapter/mailstore/leap_mailstore.py:227) in thread 139677182150400```

By far, the decrypt is dominating the longest calls. That should be priority number one to investigate.
