### ISSUE TITLE
Encrypted mail from Thunderbird shows the label "Not Encrypted"

### ISSUE THREAD

**Issue by pereiragislene** [pixelated/pixelated-user-agent#566] opened 2015-12-31 14:04 UTC
## What
When receiving encrypted mails from other mail clients (i.e.: Thunderbird), the label "Not Encrypted" is displayed. 

## Definition of done
The user should see the label "Encrypted" when receiving encrypted mails from mail clients as Thunderbird.

**Comment by varac** [comment] 2016-02-29 12:39
moving this to ready because it will confuse a big group of testers using tb/enigmail

**Comment by varac** [comment] 2016-02-29 13:37
@pereiragislene I'm not sure if you got confused between the both labels.

When I sent a signed and encrypted mail to a recent useragent (HEAD as of now), it displays the mail as "Not Signed", but properly as "Encrypted".

I composed the mail with Thunderbird/Enigmail.

**Comment by varac** [comment] 2016-02-29 13:38
@pereiragislene could you please try again and confirm which of the both labels are not displayed correctly ?

**Comment by pereiragislene** [comment] 2016-02-29 13:41
@varac: sure! I'll try and will let you know.

**Comment by pereiragislene** [comment] 2016-02-29 15:04
@varac: I sent an encrypted (not signed) mail to my pixelated account and it shows as Not Encrypted and Not Signed.
I also sent a message both encrypted and signed and it had the same labels.

<img width="771" alt="screen shot 2016-02-29 at 11 28 03" src="https://cloud.githubusercontent.com/assets/554552/13397190/9d9d2034-ded7-11e5-9c6e-e425e218a0ac.png">

**Comment by pereiragislene** [comment] 2016-02-29 19:25
@thaissiqueira and I paired and figured out that:

1. The labels are working fine when setting Enigmail to send the message using PGP/MIME.
2. The label "Not Encrypted" is displayed when sending a message encrypted using Inline PGP.

@varac: have you tried using Inline PGP? Thanks.

**Comment by varac** [comment] 2016-02-29 20:27
Thats weird. I have Enigmail configured to always use PGP/Mime, cause Inline PGP is buggy and should be avoided. Enigmail also defaults to PGP/Mime in recent versions imo.
What provider do you QA with ? I use unstable.pix because it usually has recent versions of platform/pixelated installed.

I could again reproduce sending an signed, encrypted mail from my `TB 1:38.5.1+build2-0ubuntu0.15.10.1/Enigmail 1.9 (20160223-1641)/gpg 2.0.28-3ubuntu1` to unstable, and it said ` Not signed, Encrypted`.

**Comment by varac** [comment] 2016-02-29 20:30
@pereiragislene @thaissiqueira please send me a mail from your unstable.pix accounts to my unstable.pix account (which is my nickname), and i can then send you an signed, encrypted mail to you in response.

**Comment by thaissiqueira** [comment] 2016-02-29 22:08
@varac, sent.

**Comment by varac** [comment] 2016-03-01 10:24
@thaissiqueira i didn't recieve your mail yet. Please ping me in irc and we can figure out why.

**Comment by cz8s** [comment] 2016-03-02 09:31
I can reproduce this by sending an email from mutt.
I just have to send it inline instead of pgp/mime.
This does not seem to be an error in thunderbird, but in the way we (or leap-mail)
check if the mail was encrypted.

**Comment by thaissiqueira** [comment] 2016-03-02 19:23
Ok guys.
We keep looking when the task go to Development column.

**Comment by varac** [comment] 2016-03-03 14:30
ok, i see even now two different issues here.
For the one that a signed+encrypted mail sent with TB/enigmail shows up as 'not signed', i'll open another issue.

**Comment by re-nobre** [comment] 2016-06-08 15:30
@thaissiqueira and @cacarrara, 

as you solve the #605 
what do you think we should do with this issue?

**Comment by cacarrara** [comment] 2016-06-10 17:14
Well, I've just tried to reproduce this issue using Thunderbird on Mac and I couldn't, so I'm going to move it to Ready to Launch. :)

**Comment by cacarrara** [comment] 2016-06-13 12:14
@varac since the other issue related with this one is not working when you send email from your machine, could you please try to reproduce this as well?

**Comment by varac** [comment] 2016-06-13 14:54
looks good on dev.pix !

**Comment by cacarrara** [comment] 2016-06-13 16:44
Well, so I think we can move it to Launch.

**Closed** 2016-06-14 13:01 UTC
Labels: bug, Signed/Encrypted Status
