### ISSUE TITLE
User agent doesn't come up due to an unhandled error in logging

### ISSUE THREAD

**Issue by rdevries-thoughtworks** [pixelated/pixelated-user-agent#884] opened 2016-12-13 09:36 UTC
This bug occurs now and then on different environments. The following loglines repeat every 4 minutes, all with the same process ID.

```
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: 2016-12-12 15:50:16 [log_legacy] CRITICAL Unhandled Error
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: Traceback (most recent call last):
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/log.py", line 84, in callWithContext
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: return context.call({ILogContext: newCtx}, func, *args, **kw)
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: return self.currentContext().callWithContext(ctx, func, *args, **kw)
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: return func(*args,**kw)
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: why = selectable.doRead()
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: --- <exception caught here> ---
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 1073, in doRead
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: transport = self.transport(skt, protocol, addr, self, s, self.reactor)
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/tcp.py", line 790, in __init__
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: self.startReading()
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/abstract.py", line 434, in startReading
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: self.reactor.addReader(self)
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 271, in addReader
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: EPOLLIN, EPOLLOUT)
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: File "/usr/share/python/pixelated-user-agent/local/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 255, in _add
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: self._poller.modify(fd, flags)
Dec 12 15:50:16 dev1 pixelated-user-agent[29227]: exceptions.IOError: [Errno 2] No such file or directory
```

The exception is raised on every request and prevents a response, so it looks like the process is down, though actually it isn't.

**Comment by rdevries-thoughtworks** [comment] 2016-12-13 09:39
- See https://groups.google.com/forum/#!topic/autobahnws/6EM7Frkg1dE -- it suggests changing to select reactor (instead of epoll), and mentions memory as a potential source of problems
- See http://stackoverflow.com/questions/22679377/twisted-error-in-server-with-mqtt-client -- it suggests that this is a Twisted bug (so my conclusion would be: maybe move to select reactor)

**Comment by olabini** [comment] 2017-01-20 19:12
Another duplicate of #913

**Closed** 2017-03-22 12:09 UTC
Labels: bug
