### ISSUE TITLE
deprecate the usage of requests

### ISSUE THREAD

**Issue by kalikaneko** [pixelated/pixelated-user-agent#1068] opened 2017-05-04 08:06 UTC
having requests as a dependency of a twisted-based daemon is a source of contention.
could you consider migrating the usage of requests to treq instead?
http://treq.readthedocs.io/en/latest/

**Comment by tuliocasagrande** [comment] 2017-05-05 14:00
This is a duplicate of #1060

**Closed by tuliocasagrande** 2017-05-05 14:00 UTC

**Comment by kalikaneko** [comment] 2017-05-07 13:59
ah, true, I forgot I had already opened the other one!
